# Generated by Django 5.0.5 on 2024-06-05 22:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('imagenes_empresa', models.ImageField(upload_to='')),
                ('mision', models.CharField(max_length=1500)),
                ('vision', models.CharField(max_length=600)),
                ('servicios', models.CharField(max_length=500)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.categoriaempresa')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('nombre_propietario', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('telefono', models.CharField(max_length=50)),
                ('perfil_empresa', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='general.perfilempresa')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('calificacion', models.FloatField(default=0)),
                ('fecha_valoracion', models.DateField()),
                ('comentarios', models.CharField(max_length=50000)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.empresa')),
            ],
        ),
    ]
