# Generated by Django 5.0.5 on 2024-06-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='imagenes_empresa',
            field=models.ImageField(upload_to='perfil_empresa'),
        ),
    ]
